version: "3.8"

services:
  # db service
  mongo:
    image: mongo:6.0
    container_name: reviewgram_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # app service
  app:
    build: .
    container_name: reviewgram_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
        - DATABASE_URL=mongodb://mongo:27017/movie_review
    depends_on:
      - mongo

# volume
volumes:
  mongo_data:
