version: "3.8"

services:
  # db service
  mongo:
    image: mongo:6.0
    container_name: reviewgram_db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  # app service
  app:
    build: .
    container_name: reviewgram_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/movie_review
      - NODE_ENV=production
    depends_on:
      - mongo

volumes:
  mongo_data:
